import type { EventType, IntelligenceModule, IntelligenceRule, RuleCondition } from './types';

export type RuleTemplate = Omit<IntelligenceRule, 'id' | 'organizationId' | 'createdAt' | 'updatedAt'> & {
  conditions: Omit<RuleCondition, 'id' | 'ruleId'>[];
};

export const DEFAULT_RULE_TEMPLATES: RuleTemplate[] = [
  {
    name: 'Teacher supervision gap',
    eventType: 'TeacherSupervisionGap',
    module: 'TeacherProductivity',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'no_teacher_with_students', parameters: { minStudents: 5 }, sortOrder: 0 }],
  },
  {
    name: 'Running in corridor',
    eventType: 'RunningDetected',
    module: 'Discipline',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 300,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'Running', minValue: 0.55 }, sortOrder: 0 }],
  },
  {
    name: 'Loitering detected',
    eventType: 'Loitering',
    module: 'Discipline',
    enabled: true,
    severityDefault: 'Low',
    cooldownSeconds: 300,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'Loitering', minValue: 0.5 }, sortOrder: 0 }],
  },
  {
    name: 'Room overcrowding',
    eventType: 'Overcrowding',
    module: 'StudentOccupancy',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 900,
    version: 1,
    conditions: [{ conditionType: 'person_count_over_capacity', parameters: { ratio: 1.1 }, sortOrder: 0 }],
  },
  {
    name: 'Critical camera offline',
    eventType: 'CriticalCameraOffline',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'Critical',
    cooldownSeconds: 1800,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'Offline', minValue: 0.9 }, sortOrder: 0 }],
  },
  {
    name: 'Gate congestion',
    eventType: 'GateCongestion',
    module: 'ParentExperience',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'gate_queue', parameters: { minQueue: 10 }, sortOrder: 0 }],
  },
  {
    name: 'Staff missing at gate',
    eventType: 'StaffMissingAtGate',
    module: 'StaffDeployment',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 900,
    version: 1,
    conditions: [{ conditionType: 'staff_absent_roster', parameters: { dutyType: 'Gate Duty' }, sortOrder: 0 }],
  },
  {
    name: 'Late class start',
    eventType: 'LateClassStart',
    module: 'AcademicOperations',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 1800,
    version: 1,
    conditions: [{ conditionType: 'late_period_start', parameters: { lateMinutes: 8 }, sortOrder: 0 }],
  },
  {
    name: 'Under occupancy during class',
    eventType: 'UnderOccupancy',
    module: 'StudentOccupancy',
    enabled: true,
    severityDefault: 'Low',
    cooldownSeconds: 1200,
    version: 1,
    conditions: [{ conditionType: 'person_count_under_expected', parameters: { ratio: 0.35 }, sortOrder: 0 }],
  },
  {
    name: 'Empty scheduled room',
    eventType: 'EmptyScheduledRoom',
    module: 'StudentOccupancy',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 1200,
    version: 1,
    conditions: [{ conditionType: 'empty_scheduled_room', parameters: { maxPersonCount: 2 }, sortOrder: 0 }],
  },
  {
    name: 'Corridor overload',
    eventType: 'CorridorOverload',
    module: 'SpaceUtilization',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'CrowdDensity', minValue: 0.75 }, sortOrder: 0 }],
  },
  {
    name: 'Vehicle student overlap',
    eventType: 'VehicleStudentOverlap',
    module: 'ParentExperience',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'overlap_signals', parameters: { types: ['VehicleQueue', 'PersonCount'] }, sortOrder: 0 }],
  },
  {
    name: 'Fire or smoke',
    eventType: 'FireSmokeDetected',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'Critical',
    cooldownSeconds: 60,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'FireSmoke', minValue: 0.7 }, sortOrder: 0 }],
  },
  {
    name: 'Fall detected',
    eventType: 'FallDetected',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'Critical',
    cooldownSeconds: 120,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'Fall', minValue: 0.65 }, sortOrder: 0 }],
  },
  {
    name: 'Restricted zone entry',
    eventType: 'RestrictedZoneEntry',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'zone_entry_restricted', parameters: {}, sortOrder: 0 }],
  },
  {
    name: 'Lab supervision missing',
    eventType: 'LabSupervisionMissing',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'no_teacher_with_students', parameters: { minStudents: 3 }, sortOrder: 0 }],
  },
  {
    name: 'Server room entry',
    eventType: 'ServerRoomEntry',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'Critical',
    cooldownSeconds: 300,
    version: 1,
    conditions: [{ conditionType: 'zone_entry_server_room', parameters: {}, sortOrder: 0 }],
  },
  {
    name: 'Arrival congestion',
    eventType: 'ArrivalCongestion',
    module: 'ParentExperience',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'gate_queue', parameters: { minQueue: 8 }, sortOrder: 0 }],
  },
  {
    name: 'Dispersal delay',
    eventType: 'DispersalDelay',
    module: 'ParentExperience',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'gate_queue', parameters: { minQueue: 12 }, sortOrder: 0 }],
  },
  {
    name: 'Reception queue high',
    eventType: 'ReceptionQueueHigh',
    module: 'ParentExperience',
    enabled: true,
    severityDefault: 'Low',
    cooldownSeconds: 900,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'ReceptionQueue', minValue: 6 }, sortOrder: 0 }],
  },
  {
    name: 'Early class end',
    eventType: 'EarlyClassEnd',
    module: 'TeacherProductivity',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 1800,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'ClassEndTime', minValue: 0.5 }, sortOrder: 0 }],
  },
  {
    name: 'Missed period',
    eventType: 'MissedPeriod',
    module: 'AcademicOperations',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 1800,
    version: 1,
    conditions: [{ conditionType: 'empty_scheduled_room', parameters: { maxPersonCount: 3 }, sortOrder: 0 }],
  },
  {
    name: 'Class not conducted',
    eventType: 'ClassNotConducted',
    module: 'AcademicOperations',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 1800,
    version: 1,
    conditions: [{ conditionType: 'empty_scheduled_room', parameters: { maxPersonCount: 2 }, sortOrder: 0 }],
  },
  {
    name: 'Substitute teacher detected',
    eventType: 'SubstituteTeacherDetected',
    module: 'AcademicOperations',
    enabled: true,
    severityDefault: 'Low',
    cooldownSeconds: 3600,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'SubstituteTeacherPresent', minValue: 0.6 }, sortOrder: 0 }],
  },
  {
    name: 'Low teaching zone activity',
    eventType: 'LowTeachingZoneActivity',
    module: 'TeacherProductivity',
    enabled: true,
    severityDefault: 'Low',
    cooldownSeconds: 1200,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'TeacherNearBoard', minValue: 0.25 }, sortOrder: 0 }],
  },
  {
    name: 'Staff missing at playground',
    eventType: 'StaffMissingAtPlayground',
    module: 'StaffDeployment',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 900,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'StaffPresentAtPlayground', minValue: 0.5 }, sortOrder: 0 }],
  },
  {
    name: 'Weak dispersal coverage',
    eventType: 'WeakDispersalCoverage',
    module: 'StaffDeployment',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'staff_absent_roster', parameters: { dutyType: 'Gate Duty' }, sortOrder: 0 }],
  },
  {
    name: 'Room underused',
    eventType: 'RoomUnderused',
    module: 'SpaceUtilization',
    enabled: true,
    severityDefault: 'Low',
    cooldownSeconds: 1200,
    version: 1,
    conditions: [{ conditionType: 'person_count_under_expected', parameters: { ratio: 0.25 }, sortOrder: 0 }],
  },
  {
    name: 'Unsafe climbing',
    eventType: 'UnsafeClimbing',
    module: 'Discipline',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 300,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'Running', minValue: 0.7 }, sortOrder: 0 }],
  },
  {
    name: 'Student outside class during period',
    eventType: 'StudentOutsideClassDuringPeriod',
    module: 'Discipline',
    enabled: true,
    severityDefault: 'Medium',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'ZoneEntry', minValue: 0.6 }, sortOrder: 0 }],
  },
  {
    name: 'Emergency exit crowding',
    eventType: 'EmergencyExitCrowding',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 600,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'CrowdDensity', minValue: 0.8 }, sortOrder: 0 }],
  },
  {
    name: 'Fire exit obstruction',
    eventType: 'FireExitObstruction',
    module: 'Compliance',
    enabled: true,
    severityDefault: 'High',
    cooldownSeconds: 900,
    version: 1,
    conditions: [{ conditionType: 'signal_threshold', parameters: { signalType: 'PersonCount', minValue: 15 }, sortOrder: 0 }],
  },

];

export function templatesForOrg(organizationId: number): IntelligenceRule[] {
  return DEFAULT_RULE_TEMPLATES.map((t, i) => ({
    id: i + 1,
    organizationId,
    name: t.name,
    eventType: t.eventType,
    module: t.module,
    enabled: t.enabled,
    severityDefault: t.severityDefault,
    cooldownSeconds: t.cooldownSeconds,
    version: t.version,
    createdAt: new Date().toISOString(),
  }));
}
